import { prisma } from '@/lib/prisma'
import { AuditEventType, Prisma } from '@prisma/client'

/**
 * Write an audit log entry for compliance tracking.
 *
 * CRITICAL: Audit log entries are immutable. Never update or delete them.
 * All signing events MUST write an audit log entry per legal-compliance.md.
 *
 * @param params - Audit log entry parameters
 * @returns Promise that resolves when the audit log entry is written
 *
 * @example
 * await writeAuditLog({
 *   workflowId: 'workflow_123',
 *   eventType: 'WORKFLOW_CREATED',
 *   actorId: session.user.id,
 *   ipAddress: req.headers.get('x-forwarded-for') ?? 'unknown',
 *   userAgent: req.headers.get('user-agent') ?? 'unknown',
 *   metadata: { signerCount: 3 }
 * })
 *
 * @example Auth events (no workflow context)
 * await writeAuditLog({
 *   workflowId: null,
 *   eventType: 'AUTH_SUCCESS',
 *   actorId: user.id,
 *   ipAddress: '192.168.1.1',
 *   userAgent: 'Mozilla/5.0...',
 *   metadata: { provider: 'google', email: 'user@example.com' }
 * })
 */
export async function writeAuditLog(params: {
  workflowId: string | null
  eventType: AuditEventType
  actorId: string
  ipAddress: string
  userAgent: string
  metadata?: Record<string, unknown>
}): Promise<void> {
  const { workflowId, eventType, actorId, ipAddress, userAgent, metadata } = params

  await prisma.auditLog.create({
    data: {
      workflowId: workflowId ?? undefined,
      eventType,
      actorId,
      ipAddress,
      userAgent,
      // Cast to Prisma.InputJsonValue since our Record<string, unknown> is JSON-compatible
      metadata: metadata ? (metadata as Prisma.InputJsonValue) : undefined,
      // timestamp is auto-generated by Prisma with @default(now())
      // NEVER trust client-supplied timestamps
    },
  })
}
